### ISSUE TITLE
Username & password is hardcoded to admin/admin

### ISSUE THREAD

**Issue by shuawest** [RoddieKieley/activemq-artemis-management#2]
This breaks the operator when the console authentication is enabled: 

> func NewJolokia(_ip string, _port string, _path string) *Jolokia {
> 	j := Jolokia{
> 		ip:         _ip,
> 		port:       _port,
> 		jolokiaURL: "http://admin:admin@" + _ip + ":" + _port + _path,
> 	}
> 	return &j
> }

**Comment by gaohoward** [comment]
close as fixed already.
