### ISSUE TITLE
Read and Exec results don't get unmarshaled properly

### ISSUE THREAD

**Issue by shuawest** [RoddieKieley/activemq-artemis-management#3]
The result and error handling is dropping data, and not logging the error details.  This causes the operator to continue as though everything ok, when for example an Artemis address is trying be created via CR.

**Comment by gaohoward** [comment]
this should be addressed in commit https://github.com/artemiscloud/activemq-artemis-management/commit/1e29529292a24af6a09fbf4731be7892da43ab10

**Comment by gaohoward** [comment]
close as fixed
